---
title: "Junteng Liu's Academic Homepage"
minimal_mistakes_skin: default
search: true
search_full_content: true
repository: "mcptest-user/LJT-Homepage"
analytics:
  provider: false
atom_feed:
  path: ''
header:
  teaser: /assets/images/teaser.jpg
  overlay_image: /assets/images/teaser.jpg
  overlay_filter: 0.5
logo: /assets/images/logo.png
masthead_title: " "
include: ["_pages"]
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
author:
  name: "Junteng Liu"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "First-year PhD candidate at HKUST NLP Group. Research focuses on natural language processing and machine learning."
  location: "Hong Kong"
  email: "jliugi@connect.ust.hk"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jliugi@connect.ust.hk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
---
